Scraper for Tanzania Government Gazettes
CodeForAfrica-SCRAPERS/opengazettes_tz_scrapy pull request #1
Opened 2017-08-04 12:00 UTC by ebrahim-j

**What does this PR do?**

- Adds two spiders for two _different_ domains
- Adds an Item Pipeline for download and storage of file
- Stores the gazettes in a specified directory using the specified structure eg. Year > Month
- Directs the feed exports to an online s3 bucket

**How can this be manually tested**

There is a job on scrapinghub to scrape SL gazettes
Check its s3 bucket to find the scrapped gazettes
@DavidLemayian

2017-08-08 13:56 UTC, DavidLemayian requested changes
This is looking good. Just a few slight changes requested.

2017-08-08 13:56 UTC, DavidLemayian commented on README.md
> +- Then run the command  `scrapy crawl tz_gazeyyes_v2 -a year=2016 -o sl_gazettes.jsonlines`
Might be a spelling error here. Also, should it be `tz_gazettes.jsonlines`?

2017-08-08 13:56 UTC, DavidLemayian commented on README.md
> +- `sn_gazettes.jsonlines` is the file where crawls are saved, this too can be a directory
This should match above.

2017-08-08 13:56 UTC, DavidLemayian commented on opengazettes/settings.py
> +USER_AGENT = 'opengazettes (+http://www.yourdomain.com)'
Let's have this as `gazeti.AFRICA (+https://gazeti.africa)`.

2017-08-08 13:56 UTC, DavidLemayian commented
@ebrahim-j What do you mean "There is a job on scrapinghub to scrape SL gazettes"?

2017-08-09 07:42 UTC, ebrahim-j commented on README.md
> +- Then run the command  `scrapy crawl tz_gazeyyes_v2 -a year=2016 -o sl_gazettes.jsonlines`
Oops, corrected..

2017-08-09 07:42 UTC, ebrahim-j commented on opengazettes/settings.py
> +USER_AGENT = 'opengazettes (+http://www.yourdomain.com)'
Done

2017-08-09 07:43 UTC, ebrahim-j commented
@DavidLemayian The PR has been updated with the **corrected** comment with more detail on it

2017-08-09 17:17 UTC, merged